#!/usr/bin/env python3
#
# Copyright (C) 2016 James Murphy
# Licensed under the GPL version 2 only
#
# A battery indicator blocklet script for i3blocks

from subprocess import check_output
import os
import re

config = dict(os.environ)
status = check_output(['acpi'], universal_newlines=True)

if not status:
    # stands for no battery found
    color = config.get("color_10", "#FF5555")
    fulltext = "<span color='{}'><span font='FontAwesome'> </span></span>".format(color)
    percentleft = 100
else:
    # if there is more than one battery in one laptop, the percentage left is
    # available for each battery separately, although state and remaining
    # time for overall block is shown in the status of the first battery
    batteries = status.split("\n")
    state_batteries=[]
    commasplitstatus_batteries=[]
    percentleft_batteries=[]
    time = ""
    for battery in batteries:
        if battery!='':
            state_batteries.append(battery.split(": ")[1].split(", ")[0])
            commasplitstatus = battery.split(", ")
            if not time:
                time = commasplitstatus[-1].strip()
                # check if it matches a time
                time = re.match(r"(\d+):(\d+)", time)
                if time:
                    time = ":".join(time.groups())
                    timeleft = " ({})".format(time)
                else:
                    timeleft = ""

            p = int(commasplitstatus[1].rstrip("%\n"))
            if p>0:
                percentleft_batteries.append(p)
            commasplitstatus_batteries.append(commasplitstatus)
    state = state_batteries[0]
    commasplitstatus = commasplitstatus_batteries[0]
    if percentleft_batteries:
        percentleft = int(sum(percentleft_batteries)/len(percentleft_batteries))
    else:
        percentleft = 0

    # stands for charging
    color = config.get("color_charging", "#8BE9FD")
    FA_LIGHTNING = "<span color='{}'><span font='FontAwesome'></span></span>".format(color)

    # stands for plugged in
    FA_PLUG = "<span font='FontAwesome'></span>"

    # stands for unknown status of battery
    FA_QUESTION = "<span font='FontAwesome'></span>"

    def fa_battery(percent):
        if percent < 10:
            return "<span font='FontAwesome'></span>"
        if percent < 25:
            return "<span font='FontAwesome'></span>"
        if percent < 50:
            return "<span font='FontAwesome'></span>"
        if percent < 75:
            return "<span font='FontAwesome'></span>"
        return "<span font='FontAwesome'></span>"

    if state == "Discharging":
        fulltext = fa_battery(percentleft)
    elif state == "Full":
        fulltext = FA_PLUG
        timeleft = ""
    elif state == "Unknown":
        fulltext = FA_QUESTION + FA_BATTERY
        timeleft = ""
    else:
        fulltext = FA_LIGHTNING + FA_PLUG

    def color(percent):
        if percent < 10:
            return config.get("color_10", "#FFB86C")
        if percent < 30:
            return config.get("color_30", "#FFB86C")
        if percent < 50:
            return config.get("color_50", "#F1FA8C")
        if percent < 70:
            return config.get("color_70", "#50FA7B")
        return config.get("color_full", "#F8F8F2")

    form =  '<span color="{}">{}%</span>'
    fulltext += str(percentleft)
    fulltext = form.format(color(percentleft), fulltext)
    #fulltext += timeleft

print(fulltext)
print(fulltext)
if percentleft < 10:
    exit(33)
