#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
SCREENSHOT="maim $PICTURE"

$SCREENSHOT

notify-send -a "i3 blur-lock" Locking "The screen lock process has started"

BLUR="5x5"
magick $PICTURE -noise 2 -blur $BLUR -scale 10% -scale 1000% $PICTURE

setxkbmap -layout us,ru

dunstctl set-paused true
i3lock -i $PICTURE
dunstctl set-paused false

rm $PICTURE
