#!/bin/bash

CURRENT_LAYOUT=$(setxkbmap -query | grep layout | sed 's/,\w\+//gi' | awk '{print $2}')

if [ "$CURRENT_LAYOUT" = "us" ]; then
    setxkbmap -layout ru,us
else
    setxkbmap -layout us,ru
fi
